<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MuaNgay</name>
   <tag></tag>
   <elementGuidId>8770644b-e95c-43c4-83f9-119926db24d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>form[@id='add-to-cart-form']/div[2]/div[3]/div/div/div/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
