<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>opt_District_ThuDuc</name>
   <tag></tag>
   <elementGuidId>65a58337-2b3a-4a42-b0e1-f9e8a78092bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[normalize-space(text())='TP Thủ Đức']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-district-result-xdt5-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;TP Thủ Đức&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>534ac88a-1702-41fc-aa62-073a82fc4e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--selectable select2-results__option--highlighted</value>
      <webElementGuid>56e49896-d7fc-4e18-94d4-122d7d8e3f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-district-result-xdt5-1</value>
      <webElementGuid>a1c4eff8-4bbd-4681-afc8-eb90918edf28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>204db1f4-2620-4123-b696-d06fa3a25bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-data-select2-district-result-xdt5-1</value>
      <webElementGuid>52e8d205-5041-4c65-adaf-2e1d71a2e435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bc23efcf-f8b6-4300-9855-9e351545dae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TP Thủ Đức</value>
      <webElementGuid>e4c48c94-7681-48e5-b51d-d9d6d3c6494e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-district-result-xdt5-1&quot;)</value>
      <webElementGuid>91d437a7-3378-478e-b40d-00a2f1acdeae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-district-result-xdt5-1']</value>
      <webElementGuid>c8b5ff3b-705c-43ad-af0f-d0fe2b9de6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-district-results']/li[5]</value>
      <webElementGuid>ab7e6045-20d1-468a-bd83-4756c8e35cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quận Bình Thạnh'])[2]/following::li[1]</value>
      <webElementGuid>ea50e394-643c-4885-a341-2ffd8a5feb4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quận 11'])[2]/following::li[2]</value>
      <webElementGuid>916472c9-f2be-44da-8ae3-473e7ae3c19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quận 3'])[2]/preceding::li[1]</value>
      <webElementGuid>36d3eb77-7ea5-4681-a49a-ea8ee79c6418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quận 4'])[2]/preceding::li[2]</value>
      <webElementGuid>c09af30f-964f-4d17-a6e7-d971ba289b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li[5]</value>
      <webElementGuid>3fe59870-a13d-427f-846b-ccb62e661241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-district-result-xdt5-1' and (text() = 'TP Thủ Đức' or . = 'TP Thủ Đức')]</value>
      <webElementGuid>9acc3700-b86c-447c-a8f8-a08d81f9d347</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
