<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>opt_Province_HCM</name>
   <tag></tag>
   <elementGuidId>0d21df3f-53e4-4b3c-a8e4-2c1a00c27194</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-city-result-l9b7-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[normalize-space(text())='TPHCM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;TPHCM&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f1672727-ea55-4263-92de-e8bcc7b940a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--selectable select2-results__option--highlighted</value>
      <webElementGuid>ba7cfc63-ba69-4af1-8aa4-c085fcf6425f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-city-result-l9b7-1</value>
      <webElementGuid>cd02d0ae-9f31-436c-9fd3-32db795430a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ad4f0b58-ec0d-4c17-8c3e-a327c2f9f2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-data-select2-city-result-l9b7-1</value>
      <webElementGuid>543342e3-8f05-458f-a8b2-d82e0f6275b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b2bcc57b-dc82-4164-af48-69cd03cf67f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TPHCM</value>
      <webElementGuid>9b40b924-e32b-4778-a285-e859bce561d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-city-result-l9b7-1&quot;)</value>
      <webElementGuid>c4a6025e-68e5-4732-a3eb-f3180ea638d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-city-result-l9b7-1']</value>
      <webElementGuid>a39973ff-8974-48ae-9249-443c4cde705e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-city-results']/li</value>
      <webElementGuid>030677e3-f1e7-4206-bc8d-4ea26d25c0e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn tỉnh thành'])[1]/following::li[1]</value>
      <webElementGuid>1b764831-6cf9-49a3-a874-d8ecca128c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hệ thống cửa hàng'])[2]/following::li[1]</value>
      <webElementGuid>bf7abbc7-63f5-4e1e-9d09-e856fef4ec4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hà Nội'])[2]/preceding::li[1]</value>
      <webElementGuid>fae6a66c-36d0-49d2-8644-5b7537a9b9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đà Nẵng'])[2]/preceding::li[2]</value>
      <webElementGuid>4b1745fe-5a70-425e-8356-8dff394a25d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li</value>
      <webElementGuid>782bc79f-1d2e-4485-a5d2-95a78adac703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-city-result-l9b7-1' and (text() = 'TPHCM' or . = 'TPHCM')]</value>
      <webElementGuid>e002c951-6963-4efd-8253-51830e479b01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
