<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>news</name>
   <tag></tag>
   <elementGuidId>17c36c11-5395-4641-8c63-bf64243f2720</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Hướng dẫn sử dụng ứng dụng ShopVNB mới ra mắt trên iOS &amp; Android']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Hướng dẫn sử dụng ứng dụng ShopVNB mới ra mắt trên iOS &amp; Android&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2e6e745a-5a38-4f18-94e2-f4d8c4fb00ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>f9dfdf83-876a-445d-b57a-8502e5635cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>d1a77634-e16b-4950-b630-1815aa0ab579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazyload loaded</value>
      <webElementGuid>65ef7c9c-e660-4383-a5fd-5de49f25deaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.shopvnb.com/img/600x360/uploads/tin_tuc/ung-dung-shopvnb_1763780391.webp</value>
      <webElementGuid>e127cd7d-afce-4291-86c2-862e774f3a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://cdn.shopvnb.com/img/600x360/uploads/tin_tuc/ung-dung-shopvnb_1763780391.webp</value>
      <webElementGuid>ccb8bc07-de49-4781-a254-e214ff22c924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Hướng dẫn sử dụng ứng dụng ShopVNB mới ra mắt trên iOS &amp; Android</value>
      <webElementGuid>17d1fdfc-7344-476c-8cc0-3f4973f0b91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>32493d33-f2d1-4236-b8fa-d7374c035885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;bodywrap&quot;]/div[@class=&quot;blog_wrapper layout-blog&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;right-content col-lg-9 col-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 col-md-4 col-sm-6 col-xs-12&quot;]/div[@class=&quot;item-blog&quot;]/div[@class=&quot;block-thumb&quot;]/a[@class=&quot;thumb&quot;]/img[@class=&quot;lazyload loaded&quot;]</value>
      <webElementGuid>7eb67932-5639-413c-8faa-2519d36c3da4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Hướng dẫn sử dụng ứng dụng ShopVNB mới ra mắt trên iOS &amp; Android']</value>
      <webElementGuid>e0ae21bc-7bf3-4fac-b307-9b2b073a2f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
      <webElementGuid>81738f03-cdc7-438b-842a-ff6d5915224c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.shopvnb.com/img/600x360/uploads/tin_tuc/ung-dung-shopvnb_1763780391.webp' and @alt = 'Hướng dẫn sử dụng ứng dụng ShopVNB mới ra mắt trên iOS &amp; Android']</value>
      <webElementGuid>74c9ae6c-b977-49a4-8af5-bea494cb26ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
