<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_dis</name>
   <tag></tag>
   <elementGuidId>8c9a5180-e041-453a-998b-e93dfc9313d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>id=select2-district-container</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
